In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/iammustafatz/diabetes-prediction-dataset/diabetes_prediction_dataset.csv

In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
df=pd.read_csv("/kaggle/input/datasets/iammustafatz/diabetes-prediction-dataset/diabetes_prediction_dataset.csv")
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [4]:
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [5]:
df.describe().sum()

age                    100271.482696
hypertension           100001.338000
heart_disease          100001.234013
bmi                    100220.187551
HbA1c_level            100035.898179
blood_glucose_level    100957.766196
diabetes               100001.363883
dtype: float64

In [6]:
df.duplicated().sum()

np.int64(3854)

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 96146 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gender               96146 non-null  object
 1   age                  96146 non-null  float64
 2   hypertension         96146 non-null  int64
 3   heart_disease        96146 non-null  int64
 4   smoking_history      96146 non-null  object
 5   bmi                  96146 non-null  float64
 6   HbA1c_level          96146 non-null  float64
 7   blood_glucose_level  96146 non-null  int64
 8   diabetes             96146 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 7.3+ MB

In [9]:
df.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [10]:
df["smoking_history"].value_counts()

smoking_history
never          34398
No Info        32887
former          9299
current         9197
not current     6367
ever            3998
Name: count, dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder
xy=LabelEncoder()
df["gender"]=xy.fit_transform(df["gender"])

In [12]:
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0,80.0,0,1,never,25.19,6.6,140,0
1,0,54.0,0,0,No Info,27.32,6.6,80,0
2,1,28.0,0,0,never,27.32,5.7,158,0
3,0,36.0,0,0,current,23.45,5.0,155,0
4,1,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99994,0,36.0,0,0,No Info,24.60,4.8,145,0
99996,0,2.0,0,0,No Info,17.37,6.5,100,0
99997,1,66.0,0,0,former,27.83,5.7,155,0
99998,0,24.0,0,0,never,35.42,4.0,100,0
99999,0,57.0,0,0,current,22.43,6.6,90,0

In [13]:
df=pd.get_dummies(df,columns=["smoking_history"])
df

,gender,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes,smoking_history_No Info,smoking_history_current,smoking_history_ever,smoking_history_former,smoking_history_never,smoking_history_not current
0,0,80.0,0,1,25.19,6.6,140,0,False,False,False,False,True,False
1,0,54.0,0,0,27.32,6.6,80,0,True,False,False,False,False,False
2,1,28.0,0,0,27.32,5.7,158,0,False,False,False,False,True,False
3,0,36.0,0,0,23.45,5.0,155,0,False,True,False,False,False,False
4,1,76.0,1,1,20.14,4.8,155,0,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99994,0,36.0,0,0,24.60,4.8,145,0,True,False,False,False,False,False
99996,0,2.0,0,0,17.37,6.5,100,0,True,False,False,False,False,False
99997,1,66.0,0,0,27.83,5.7,155,0,False,False,False,True,False,False
99998,0,24.0,0,0,35.42,4.0,100,0,False,False,False,False,True,False
99999,0,57.0,0,0,22.43,6.6,90,0,False,True,False,False,False,False

In [14]:
x=df.drop("diabetes",axis=1)
y=df["diabetes"]

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=10)

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [17]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()

In [18]:
lg.fit(X_train,Y_train)

LogisticRegression()

In [19]:
pred=lg.predict(X_test)

In [20]:
print(type(pred))
print(len(pred))

<class 'numpy.ndarray'>
19230

In [21]:
pred[:10]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [22]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test, pred)
print(accuracy)

0.9585023400936038

In [23]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(Y_test, pred))
print(confusion_matrix(Y_test, pred))

              precision    recall  f1-score   support

           0       0.96      0.99      0.98     17512
           1       0.88      0.62      0.73      1718

    accuracy                           0.96     19230
   macro avg       0.92      0.81      0.85     19230
weighted avg       0.96      0.96      0.96     19230

[[17362   150]
 [  648  1070]]

In [24]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)

In [25]:
knn.fit(X_train, Y_train)

KNeighborsClassifier()

In [26]:
knn_pred = knn.predict(X_test)

In [27]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test,knn_pred)
print(accuracy)

0.9577223088923557

In [28]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(Y_test,knn_pred))
print(confusion_matrix(Y_test,knn_pred))

              precision    recall  f1-score   support

           0       0.96      0.99      0.98     17512
           1       0.88      0.61      0.72      1718

    accuracy                           0.96     19230
   macro avg       0.92      0.80      0.85     19230
weighted avg       0.96      0.96      0.95     19230

[[17363   149]
 [  664  1054]]

In [29]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(random_state=42)

In [30]:
tree.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=42)

In [31]:
tree_pred = tree.predict(X_test)

In [32]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test,tree_pred)
print(accuracy)

0.9507540301612064

In [33]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(Y_test,tree_pred))
print(confusion_matrix(Y_test,tree_pred))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97     17512
           1       0.72      0.74      0.73      1718

    accuracy                           0.95     19230
   macro avg       0.85      0.86      0.85     19230
weighted avg       0.95      0.95      0.95     19230

[[17006   506]
 [  441  1277]]

In [34]:
from sklearn.metrics import accuracy_score
print("Logistic:", accuracy_score(Y_test,pred))
print("KNN:",accuracy_score(Y_test, knn_pred))
print("Decision Tree:",accuracy_score(Y_test, tree_pred))

Logistic: 0.9585023400936038
KNN: 0.9577223088923557
Decision Tree: 0.9507540301612064

In [35]:
from sklearn.metrics import classification_report
print(classification_report(Y_test, pred))
print(classification_report(Y_test, knn_pred))
print(classification_report(Y_test, tree_pred))

              precision    recall  f1-score   support

           0       0.96      0.99      0.98     17512
           1       0.88      0.62      0.73      1718

    accuracy                           0.96     19230
   macro avg       0.92      0.81      0.85     19230
weighted avg       0.96      0.96      0.96     19230

              precision    recall  f1-score   support

           0       0.96      0.99      0.98     17512
           1       0.88      0.61      0.72      1718

    accuracy                           0.96     19230
   macro avg       0.92      0.80      0.85     19230
weighted avg       0.96      0.96      0.95     19230

              precision    recall  f1-score   support

           0       0.97      0.97      0.97     17512
           1       0.72      0.74      0.73      1718

    accuracy                           0.95     19230
   macro avg       0.85      0.86      0.85     19230
weighted avg       0.95      0.95      0.95     19230